import Foundation
import Testing
@testable import OpenIslandCore

struct ClaudeTranscriptDiscoveryTests {
    @Test
    func stripsLocalCommandCaveatMarkers() {
        let input = """
        <local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>
        """
        let stripped = ClaudeTranscriptDiscovery.stripTranscriptMarkers(input)
        #expect(!stripped.contains("<"))
        #expect(!stripped.contains(">"))
        #expect(stripped.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
    }

    @Test
    func stripsLocalCommandStdoutMarkers() {
        let input = "<local-command-stdout>On branch main</local-command-stdout>"
        let stripped = ClaudeTranscriptDiscovery.stripTranscriptMarkers(input)
        #expect(stripped.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
    }

    @Test
    func keepsSlashCommandVisibleWhenUnwrappingCommandName() {
        let input = """
        <command-name>/commit</command-name>
        <command-message>commit</command-message>
        <command-args></command-args>
        """
        let stripped = ClaudeTranscriptDiscovery.stripTranscriptMarkers(input)
        #expect(stripped.contains("/commit"))
        #expect(!stripped.contains("<"))
        #expect(!stripped.contains(">"))
    }

    @Test
    func preservesRegularUserPromptText() {
        let input = "Fix the bug in the login flow"
        let stripped = ClaudeTranscriptDiscovery.stripTranscriptMarkers(input)
        #expect(stripped == input)
    }

    @Test
    func dropsStrayTagShards() {
        let input = "hello <unknown-tag> world </something>"
        let stripped = ClaudeTranscriptDiscovery.stripTranscriptMarkers(input)
        #expect(!stripped.contains("<"))
        #expect(!stripped.contains(">"))
        #expect(stripped.contains("hello"))
        #expect(stripped.contains("world"))
    }
}
